---
permalink: pretty
title: '"Uncle Tom''s story of his life"  an autobiography of the Rev. Josiah Henson
  (Mrs. Harriet Beecher Stowe''s "Uncle Tom") : from 1789 to 1876 '
tagline: ", an annotated digital edition"
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url: 
baseurl: ''
author:
  name: An Author
  url: 
  email: 
  twitter: 
version: 0.6
homepage_image: http://readux.library.emory.edu/books/emory:b5j2m/pages/emory:gnskh/single-page/
show_annotation_author: true
source_info:
  title: '"Uncle Tom''s story of his life"  an autobiography of the Rev. Josiah Henson
    (Mrs. Harriet Beecher Stowe''s "Uncle Tom") : from 1789 to 1876 '
  author: Henson, Josiah, 1789-1883.
  date: '1876'
  url: http://readux.library.emory.edu/books/emory:b5j2m/
  pdf_url: http://readux.library.emory.edu/books/emory:b5j2m/pdf/#page=2
  via_readux: true
publication_info:
  title: '"Uncle Tom''s story of his life"  an autobiography of the Rev. Josiah Henson
    (Mrs. Harriet Beecher Stowe''s "Uncle Tom") : from 1789 to 1876 , an annotated
    digital edition'
  date: '2016'
  author: Henson, Josiah, 1789-1883.
  editors:
  - Jesse Pearlman Karlsberg
  tei_xml: tei.xml
image_size:
  page:
    width: 733
    height: 1000
  thumbnail:
    width: 219
    height: 300
  small-thumbnail:
    width: 73
    height: 100
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
